---
title: "About"
author: "Michelle Kendall"
date: "04/03/2020"
output: html_document
---

<!-- NB you need to perform
     library(knitr)
     knit(about.Rmd)
     to create the md file
     to be used in the shiny app -->
    
# About

This Shiny app is created and maintained by <a href="https://michellekendall.github.io/" target="_blank">Michelle Kendall</a>. 

This version contains data from the entire epidemic in England and Wales, where available, and is such rather slow. 
For a faster version with only 2021 data, please visit [LocalCovidTracker-2021](https://bdi-pathogens.shinyapps.io/LocalCovidTracker/).

The tabs "March-June Pillar 1 tracker" and "March-June Pillar 1 synthetic controls" provide an interactive version of the results of [1].

The "Daily tracker" tab which is updated daily builds upon our published analysis, using a shorter waiting time between infection and swab date to reflect shorter times to Pillar 2 testing.

The "Map tracker" tab presents the same results as the "Daily tracker" but visualised using maps. We thank Will Probert for providing shapefiles and code towards this.

The "Cases by age" tab presents an analysis developed by Robert Hinch and Michelle Kendall and is also updated daily.

The source code is available on [GitHub](https://github.com/BDI-pathogens/LocalCovidTracker). 
Please let us know of any issues or requests via the [Issues](https://github.com/BDI-pathogens/LocalCovidTracker/issues) page.

<br>

[1] Michelle Kendall, Luke Milsom, Lucie Abeler-Dörner, Chris Wymant, Luca Ferretti, Mark Briers, Chris Holmes, David Bonsall, Johannes Abeler, Christophe Fraser. <a href="http://www.thelancet.com/journals/landig/article/PIIS2589-7500(20)30241-7/fulltext" target="_blank">  Epidemiological changes on the Isle of Wight after the launch of the NHS Test and Trace programme: a preliminary analysis</a>, <i>The Lancet Digital Health</i>,  Volume 2, Issue 12, E658-E666, December 01, 2020.




